apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftp-pvc
  namespace: udh-pipeline # Ensure this is the same namespace as your pod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed
  storageClassName: longhorn  # Use the correct StorageClass if necessary

