apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: udh-pipeline
data:
  config.yml: |
    kafka:
      clusters:
        - name: local
          bootstrapServers: "kafka:9092"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: udh-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/kafkaui
              readOnly: true
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"
      volumes:
        - name: config-volume
          configMap:
            name: kafka-ui-config

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: udh-pipeline
spec:
  selector:
    app: kafka-ui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30380
      protocol: TCP
      name: http
  type: NodePort

