apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-proxy
  namespace: udh-pipeline
subsets:
  - addresses:
      - ip: 192.168.29.51
    ports:
      - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-proxy
  namespace: udh-pipeline
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  clusterIP: None

