apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hive-extra-lib-pvc
  namespace: udh-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

