version: '3.8'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager/alert.rules.yml:/etc/prometheus/alert.rules.yml
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    environment:
      KAFKA_SERVER: "your-kafka:9092"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://user:password@postgres:5432/postgres?sslmode=disable"

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: public
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  ldap-exporter:
    image: tomcz/openldap_exporter
    container_name: ldap-exporter
    ports:
      - "9330:9330"
    environment:
      LDAP_URI: ldap://your-ldap:389

  airflow-exporter:
    image: prom/statsd-exporter
    container_name: airflow-exporter
    ports:
      - "9112:9102"
    command:
      - "--statsd.listen-udp=:9125"
      - "--web.listen-address=:9102"

  trino-exporter:
    image: bitnami/jmx-exporter
    container_name: trino-exporter
    ports:
      - "9404:9404"
    environment:
      - JAVA_OPTS=-javaagent:/opt/bitnami/jmx-exporter/jmx_prometheus_javaagent-0.18.0.jar=9404:/opt/bitnami/jmx-exporter/config.yaml
    volumes:
      - ./jmx/config.yaml:/opt/bitnami/jmx-exporter/config.yaml

  ftp-exporter:
    image: alpine
    container_name: ftp-exporter
    entrypoint: ["sh", "-c", "while true; do echo 'ftp_up 1' > /ftp/ftp.prom; sleep 15; done"]
    ports:
      - "9120:9120"
    volumes:
      - ./ftp:/ftp

volumes:
  grafana-storage:
  minio-data:

